<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZobdqcn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZobdqcn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZobdqcn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZobdqcn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZobdqcn\appProdProjectContainer([
    'container.build_hash' => 'Zobdqcn',
    'container.build_id' => 'e1d473ba',
    'container.build_time' => 1611036045,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZobdqcn');
